name: Publish Python Package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          poetry install
      - name: Build and publish
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          poetry build
          poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
